backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: HomePage
    label: Home Page
    description: home Page data
    files:
    - label: HomePage Hero
      name: HomePage Hero
      file: content/homePage/hero.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - { label: Button Name, name: buttonName, widget: string }
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: '/images/genome_image.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}

    - label: Section 1
      name: section1
      file: content/homePage/section1.md
      fields:
        - { label: Title, name: title, widget: string}
        - label: content
          name: content
          widget: list
          fields:
            - { label: Description, name: description, widget: string }
    - label: Section 2
      name: section2
      file: content/homePage/section2.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - label: Image
          name: illustrationImage
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: /images/homepage_image_part3.png, choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
    - label: Section 3
      name: section3
      file: content/homePage/section3.md
      fields:
        - { label: Title, name: title, widget: string}
        - label : content
          name : content
          widget : list
          fields:
            - { label: Description, name: description, widget: string }
    - label: Section 4
      name: section4
      file: content/homePage/section4.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - { label : Link Name, name: nameLink, widget: string}
        - label: Image
          name: illustrationImage
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: /images/homepage_image_part4.png, choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
        - label : tools & workflow
          name : tabs
          widget : list
          fields:
            - { label: Name, name: name, widget: string }
            - { label: Link GitHub, name: link, widget: string }
            - label : content
              name : content
              widget : list
              fields:
                - { label: Paragraph, name: paragraph, widget: string }
            - label: workflow 
              name: workflow
              widget: list
              fields:
                - { label: Paragraph, name: paragraph, widget: string }

  - name: AboutPage
    label: About Page
    description: About Page data
    files:
    - label: About Hero
      name: About Hero
      file: content/aboutPage/hero.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string}
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: '/images/about_hero-min.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
    - label: Researchers
      name: researchers
      file: content/aboutPage/researchers.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Lab description, name: description, widget: string}
        - { label: Lab name, name: nameLab, widget: string}
        - { label: Lab link, name: linkLab, widget: string}
        - { label: Orcid link, name: linkOrcid, widget: string}
        - { label: Scholar Google link, name: linkGoogleScholar, widget: string}
        - label : researcher
          name : researcher
          widget : list
          fields:
            - { label: name, name: name, widget: string }
            - { label: job, name: job, widget: string }
            - { label: profile, name: profile, widget: string }
            - { label: Scholar Google link, name: linkGoogleScholar, widget: string }
            - { label: Orcid link, name: linkOrcid, widget: string }
            - { label: ID photo, name: imageUrl, widget: image, choose_url: true, media_folder: 'public/images', public_folder: '/images' }
  - name: Resources Page
    label: Resources Page
    description: resources data
    files: 
    - label: Resources Hero
      name: Resources Hero
      description: resources Page data
      file: content/resources/hero.md
      fields:
          - { label: Title, name: title, widget: string}
          - { label: Description, name: description, widget: string}
          - label: Image
            name: imageHero
            widget: list
            fields : 
              - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: '/images/resources_image.png', choose_url: true}
              - { label: Alt Image , name: alt, widget: string}
    - label : Resources 
      name: Resources
      folder: content/resources
      create: true
      slug: "{{slug}}"
      file: content/resources/{{slug}}.md
      fields : 
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string}
        - { label: Content, name: contentResources, widget: string}
        - { label: subTitle, name: subTitle, widget: string}
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Url Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: '/images/hero_tools.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
        - label: Image Resources
          name: imageResources
          widget: list
          fields : 
            - { label: Url Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
    - label: Tools resources
      name: Tools resources
      description: Tools Resources Page data
      file: content/resources/tools.md
      fields: 
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string}
        - { label: subTitle, name: subTitle, widget: string }
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: '/images/hero_tools.png'}
            - { label: Alt Image , name: alt, widget: string}
        - label: tools
          name: tools
          widget: list
          fields:
            - { label: name, name: name, widget: string }
            - { label: inputFiles, name: inputFiles, widget: string }
            - { label: outputFiles, name: outputFiles, widget: string }
            - { label: informationObtained, name: informationObtained, widget: string }
            - { label: utility, name: utility, widget: string }
            - { label: peeks, name: peeks, widget: string }
            - { label: drawbacks, name: drawbacks, widget: string }

  - name : Add Resources 
    label: Add Resources
    folder: content/resources
    create: true
    slug: "{{slug}}"
    fields : 
      - { label: Title, name: title, widget: string}
      - { label: Description, name: description, widget: string}
      - { label: Content, name: contentResources, widget: string}
      - { label: subTitle, name: subTitle, widget: string}
      - label: Image
        name: imageHero
        widget: list
        fields : 
          - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', default: '/images/hero_tools.png', choose_url: true}
          - { label: Alt Image , name: alt, widget: string}
      - label: Image
        name: imageResources
        widget: list
        fields : 
          - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images', choose_url: true}
          - { label: Alt Image , name: alt, widget: string}

  - name: Thanks 
    label: Thanks 
    description: Thanks data
    files:
    - label: Content Thanks
      name: content
      file: content/thanks/datas.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - { label: linkUrl, name: linkUrl, widget: string }
        - { label: linkName, name: linkName, widget: string }
  - name: Form
    label: Form
    description: Form
    files:
    - label: Content form
      name: content 
      file: content/contactForm/datasContactForm.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - label: Image
          name: imageForm
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images',default: '/images/about_contact-min.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}

  - name: Terms Of Use
    label: Terms Of Use
    description: Terms Of Use data
    files:
    - label: Terms Of Use Hero
      name: Terms Of Use Hero
      file: content/termsOfUse/hero.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images',default: '/images/about_hero-min.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
    - label: Terms Of Use Content
      name: Terms Of Use Content
      file: content/termsOfUse/datasTermsOfUse.md
      fields:
        - label : content
          name : content
          widget : list
          fields:
            - { label: title, name: title, widget: string }
            - { label: paragraph, name: paragraph, widget: string }
  - name: Terms Of Service
    label: Terms Of Service
    description: Terms Of Service data
    files:
    - label: Terms Of Service Hero
      name: Terms Of Service Hero
      file: content/termsOfService/hero.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images',default: '/images/about_hero-min.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
    - label: Terms Of Service Content
      name: Terms Of Service Content
      file: content/termsOfService/datasTermsOfService.md
      fields:
        - label : content
          name : content
          widget : list
          fields:
            - { label: title, name: title, widget: string }
            - { label: paragraph, name: paragraph, widget: string }
  - name: Privacy Policy
    label: Privacy Policy
    description: Privacy Policy data
    files:
    - label: Privacy Policy Hero
      name: Privacy Policy Hero
      file: content/PrivacyPolicy/hero.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Description, name: description, widget: string }
        - label: Image
          name: imageHero
          widget: list
          fields : 
            - { label: Image, name: url, widget: image, media_folder: 'public/images', public_folder: '/images',default: '/images/about_hero-min.png', choose_url: true}
            - { label: Alt Image , name: alt, widget: string}
    - label: Privacy Policy Content
      name: Privacy Policy Content
      file: content/PrivacyPolicy/datasPrivacyPolicy.md
      fields:
        - label : content
          name : content
          widget : list
          fields:
            - { label: title, name: title, widget: string }
            - { label: paragraph, name: paragraph, widget: string }

